/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hardware_jni_HardwareJNI */

#ifndef _Included_hardware_jni_HardwareJNI
#define _Included_hardware_jni_HardwareJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    setLeftSpeed
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hardware_jni_HardwareJNI_setLeftSpeed
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    setRightSpeed
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_hardware_jni_HardwareJNI_setRightSpeed
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    getPoseX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hardware_jni_HardwareJNI_getPoseX
  (JNIEnv *, jclass);

/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    getPoseY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hardware_jni_HardwareJNI_getPoseY
  (JNIEnv *, jclass);

/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    getPoseTheta
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hardware_jni_HardwareJNI_getPoseTheta
  (JNIEnv *, jclass);

/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    getLeftDistance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hardware_jni_HardwareJNI_getLeftDistance
  (JNIEnv *, jclass);

/*
 * Class:     hardware_jni_HardwareJNI
 * Method:    getRightDistance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_hardware_jni_HardwareJNI_getRightDistance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
